### ISSUE TITLE
The $value type hint is incorrect

### ISSUE THREAD

**Issue by peter279k** [krowinski/tinyID#2]
According to this [code](https://github.com/krowinski/tinyID/blob/b8cb45d20852d47c93f26d62bd6cbd11b5096ff7/src/TinyID/TinyID.php#L56), the `$value` type hint is `string` and it defines in the comment block.

But the next line does the numeric condition checking block.

I think it should add the casting `int` type to make this code clear.

**Comment by krowinski** [comment]
hmm there is problem with (int) for big numbers like 

```
php -r "var_dump((int)11111111111111111111111111111111111);"
Command line code:1:
int(-6917529027641081856)
```

I string its *almost* ok
```
php -r "var_dump((int)'11111111111111111111111111111111111');"
Command line code:1:
int(9223372036854775807)
```

And not casting work better here 
```
php -r "var_dump('11111111111111111111111111111111111' > 0);"                                                                                                                 254 ↵
Command line code:1:
bool(true)
php -r "var_dump(11111111111111111111111111111111111 > 0);"
Command line code:1:
bool(true)
```

I think using BC::comp will be better here.

**Comment by peter279k** [comment]
@krowinski, thank you for your reply :).
I close the related PR and you fix this issue by yourself?

I glad you notice this issue again.

**Comment by krowinski** [comment]
I will

**Comment by krowinski** [comment]
done
