### ISSUE TITLE
Consider adding the type hints

### ISSUE THREAD

**Issue by peter279k** [krowinski/tinyID#8]
As title, the source codes in this repository lacks the comments.

Such as parameter type hints, return type hints and so on.

We can consider following two approaches to complete issue:

- Using the `phpDocumentor` style to write the comment annotations about these type hints.
- Using the [type hints](http://docs.php.net/manual/da/language.oop5.typehinting.php) of PHP features and the return type hints will be supported completely since `php-7.1` version.

**Comment by krowinski** [comment]
done
